spring:
  integration:
    xml:
      locations:
        - optional:file:/spi/config/spi-config.xml  # Your actual path
      validate-schema: false
  xml:
    ignore-dtd: true
    ignore-schema-location: true

# Add JVM args for schema resolution
server:
  port: 8080

# Logging to debug schema issues
logging:
  level:
    org.springframework.beans.factory.xml: DEBUG
    org.springframework.integration: INFO