 
server:
  port: 8080

spring:
  application:
    name: spi-app
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework.integration: INFO
    com.ads.apiseng: DEBUG

# Custom Application Configuration
spi-app:
  # Channel Configuration
  channels:
    enabled: true
    content-router:
      enabled: true
      parallel-processing: true
      error-handling: true
    original-transformer:
      enabled: true
    pub-sub:
      enabled: true
      
  # Router Configuration  
  routing:
    xml-types:
      customer:
        enabled: true
        channel: "customerProcessingChannel"
        transformer: "customerTransformer"
        subscribers: ["audit", "notification", "analytics"]
      order:
        enabled: true
        channel: "orderProcessingChannel" 
        transformer: "orderTransformer"
        subscribers: ["inventory", "shipping", "billing"]
      product:
        enabled: true
        channel: "productProcessingChannel"
        transformer: "productTransformer" 
        subscribers: ["catalog", "pricing", "recommendations"]
      invoice:
        enabled: true
        channel: "invoiceProcessingChannel"
        transformer: "invoiceTransformer"
        subscribers: ["accounting", "payment", "archive"]
      user:
        enabled: true
        channel: "userProcessingChannel"
        transformer: "userTransformer"
        subscribers: ["authentication", "profile", "permissions"]
      generic:
        enabled: true
        channel: "genericProcessingChannel"
        transformer: "genericTransformer"
        subscribers: ["logging"]
        
  # Pub/Sub Configuration
  pubsub:
    message-broker:
      type: "in-memory" # Options: in-memory, redis, rabbitmq
      enabled: true
    topics:
      xml-processed: "xml.processed"
      customer-events: "customer.events"
      order-events: "order.events"
      product-events: "product.events"
      system-events: "system.events"
    subscribers:
      audit:
        enabled: true
        topics: ["xml.processed", "customer.events", "order.events"]
        async: true
      notification:
        enabled: true
        topics: ["customer.events", "order.events"]
        async: true
      analytics:
        enabled: true
        topics: ["xml.processed", "product.events", "system.events"]
        async: true
      inventory:
        enabled: true
        topics: ["order.events", "product.events"]
        async: true
      shipping:
        enabled: false
        topics: ["order.events"]
        async: true
      billing:
        enabled: true
        topics: ["order.events", "customer.events"]
        async: true
      catalog:
        enabled: true
        topics: ["product.events"]
        async: false
      pricing:
        enabled: true
        topics: ["product.events"]
        async: true
      recommendations:
        enabled: false
        topics: ["product.events", "customer.events"]
        async: true
      accounting:
        enabled: true
        topics: ["order.events"]
        async: true
      payment:
        enabled: true
        topics: ["order.events"]
        async: false
      archive:
        enabled: true
        topics: ["xml.processed"]
        async: true
      authentication:
        enabled: true
        topics: ["customer.events"]
        async: false
      profile:
        enabled: true
        topics: ["customer.events"]
        async: true
      permissions:
        enabled: true
        topics: ["customer.events"]
        async: true
      logging:
        enabled: true
        topics: ["xml.processed", "system.events"]
        async: true
        
  # Processing Configuration
  processing:
    thread-pool-size: 10
    timeout-ms: 5000
    retry-attempts: 3
    enable-metrics: true
    enable-tracing: true
    
  # Error Handling
  error-handling:
    dead-letter-queue: true
    error-channel: "errorChannel"
    retry-policy: "exponential-backoff"
    max-retry-attempts: 3